In [1]:
import numpy as np

In [2]:
arr: np.array = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.dtype

dtype('int64')

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2.shape

(3, 3)

In [9]:
arr2[:, 1]

array([2, 5, 8])

In [10]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
arr2 + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
mask = arr2 % 2 == 0
arr2[mask]

array([2, 4, 6, 8])

In [29]:
arr3 = np.array([2,4,6,8,10,12,14,16,18,20])

In [30]:
arr2.sum()

45

In [31]:
arr3.mean()

11.0

In [32]:
arr3.max()

20

In [33]:
arr3.min()

2

In [34]:
arr4 = np.arange(1,10).reshape((3,3))

In [35]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr4.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
from numpy.linalg import inv,det

In [38]:
det(arr4)

-9.51619735392994e-16

In [39]:
inv(arr4)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [40]:
arr5 = np.array([1, 2, np.nan, 4])

In [41]:
arr5

array([ 1.,  2., nan,  4.])

In [42]:
np.nan_to_num(arr5, nan=0)

array([1., 2., 0., 4.])

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save("array.npy", arr)
loaded_arr = np.load("array.npy")